name: Build Debian & PXVIRT

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [standard, pxvirt]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Free up disk space
      run: |
        # Debian rootfs takes 8GB, so we need to aggressively free space on the runner
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        
    - name: Create empty network config
      run: |
        cp example-network.config network.config
        
    - name: Build Image (Standard)
      if: matrix.variant == 'standard'
      run: |
        sudo ./build_debian.sh
        
    - name: Build Image (PXVIRT)
      if: matrix.variant == 'pxvirt'
      run: |
        sudo ./build_debian.sh --with-pxvirt
        
    - name: Compress artifacts
      run: |
        # Use sparse compression to handle the 8GB root.img efficiently
        tar -Sczvf daisy-debian-${{ matrix.variant }}.tar.gz -C output .
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: daisy-debian-${{ matrix.variant }}-images
        path: daisy-debian-${{ matrix.variant }}.tar.gz
        retention-days: 7
